### ISSUE TITLE
tusimple

### ISSUE THREAD

**Issue by usperyang** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#1]
你好，请问genLaneNet可以使用tusimple训练吗？label里是不是会有缺失的部分

**Comment by vanilla000** [comment]
> 
> 
> 你好，请问genLaneNet可以使用tusimple训练吗？label里是不是会有缺失的部分

请问你这个训练出来了吗？

**Comment by yuliangguo** [comment]
> 你好，请问genLaneNet可以使用tusimple训练吗？label里是不是会有缺失的部分

Sorry for the late response. If you want to train on tusimple, you should remove all the 'z' part. However, because tusimple only includes 2D lanelines, it can only produce 2D laneline results. In this sense, a STOA 2d segmentation network can achieve the best result already. The overall design of our work may not be necessary.
