### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by garryz94** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#2]
In **Batch Testing** of README.md:

> Set 'args.dataset_name' to a certain data split to train the model

Is it supposed to be "Set 'args.dataset_name' to a certain data split to **test** the model"?

**Comment by JetBelson** [comment]
Great work! Thanks for sharing.

When I tried to replace the image _0000101.jpg_ in the example directory with a google street image, the result is bad. 
Then I noticed that the input also require the camera parameters (height and pitch angle)... 

The predicted camera parameters (pre_cam) are fixed when the pre-trained model is fed with different images. Is it because that the pre-trained model used the fixed camera parameters?

Is it possible to use the pre-trained model to predict 3D lanes from a single image without camera parameters?

**Comment by yuliangguo** [comment]
Thank you for pointing out. It is corrected.
